### ISSUE TITLE
datasets not found in repo

### ISSUE THREAD

**Issue by andrewbejjani** [ai4netzero/Infinite_Texture_GANs#1]
laoding channels ...
Traceback (most recent call last):
  File "`x/../Infinite_Texture_GANs/train.py`", line 67, in <module>
    dataloader,train_data = prepare_data(args)
  File "`x/../Infinite_Texture_GANs/utils.py`", line 304, in prepare_data
    from datasets import datasets_classes
`ImportError: cannot import name 'datasets_classes' from 'datasets' (unknown location)`

**Comment by Alhasan-Abdellatif** [comment]
Thanks for noticing the missing file. The datasets folder is now added with the correct files.
